name: API tests

on:
  push:
    branches:
      - main  # Запускать workflow, когда будет сделан коммит в ветку main
  pull_request:
    branches:
      - main  # Запускать workflow, когда будет сделан pull request в ветку main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7  # Используем GitHub Action для клонирования репозитория

      - name: Set up Python
        uses: actions/setup-python@v7  # Используем GitHub Action для установки Python
        with:
          python-version: '3.13'

      - name: Clone test server repository
        run: git clone https://github.com/Nikita-Filonov/qa-automation-engineer-api-course.git

      - name: Install test server dependencies
        run: pip install -r qa-automation-engineer-api-course/requirements.txt

      - name: Start a test server
        env:
          APP_HOST: "http://localhost:8000"
          DATABASE_URL: "sqlite+aiosqlite:///./local.db" # Устанавливаем URL локальной базы данных
          JWT_ALGORITHM: "HS256"
          JWT_SECRET_KEY: "qa-automation-engineer-api-course-secret-key"
          JWT_ACCESS_TOKEN_EXPIRE: 1800
          JWT_REFRESH_TOKEN_EXPIRE: 5184000
        run: uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir ./qa-automation-engineer-api-course & # Запускаем сервер с указанными переменными окружения

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests with pytest and generate Allure results
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses=2

      # Восстанавливаем историю покрытия из кеша
      - name: Restore Coverage history
        uses: actions/cache/restore@v6
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}
          restore-keys: |
            coverage-history-

      # Генерируем HTML-отчет и обновляем историю
      - name: Generate Coverage report
        run: |
          swagger-coverage-tool save-report

      # Сохраняем историю обратно в кеш
      - name: Cache Coverage  history
        if: always()
        uses: actions/cache/save@v6
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}

      # Загружаем HTML-отчет как артефакт
      - name: Upload Coverage report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage.html

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v7  # Сохраняем результаты тестов как артефакт для следующей джобы
        with:
          name: allure-results
          path: allure-results

  publish-report:
    if: always()
    needs: [ run-tests ]
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7  # Используем GitHub Action для клонирования репозитория

      - name: Download Allure results
        uses: actions/download-artifact@v8  # Загружаем результаты тестов, сохранённые джобой run-tests
        with:
          name: allure-results
          path: allure-results

      - name: Generates Allure Report with history
        uses: simple-elf/allure-report-action@v1.15  # Используем готовое решение из GitHub Marketplace для генерации Allure отчёта
        if: always()
        with:
          allure_results: allure-results  # Указываем каталог с результатами тестов
          allure_history: allure-history  # Указываем каталог для истории отчётов Allure

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4  # Используем GitHub Action для публикации отчёта на GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Токен для аутентификации на GitHub ---
          publish_branch: gh-pages
          publish_dir: allure-history
